# Generated by Django 4.2.16 on 2026-03-14 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('studio', 'Studio'), ('land', 'Land')], max_length=20)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('shortlet', 'Short-let')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city_state', models.CharField(max_length=100)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('size_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('furnishing', models.CharField(blank=True, choices=[('fully', 'Fully Furnished'), ('semi', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='properties/images/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='properties/images/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='properties/images/')),
                ('ownership_document', models.FileField(blank=True, null=True, upload_to='properties/docs/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('inquiries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
