# Generated by Django 4.2.16 on 2026-03-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_inquiry'),
        ('properties', '0003_add_description'),
    ]

    operations = [
    ]
